name: Continuous Integration

on:
  push:
    tags:
      - '*'
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
  workflow_dispatch:

jobs:
  build:
    name: Build via Docker Compose
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build plugin inside container
      run: docker compose -f docker-compose.yml up --build --abort-on-container-exit

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: structured-package
        path: dockerbuild/package

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: structured-package
        path: ./dockerbuild/package

    - name: Archive package
      run: |
        version="${GITHUB_REF#refs/tags/}"
        tar -czf ServerListPlayerFix-${version}.tar.gz -C dockerbuild/package .

    - name: Upload release archive
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ServerListPlayerFix-*.tar.gz
        tag: ${{ github.ref }}
        file_glob: true
        release_name: "${{ github.ref_name }} - Download"
